
export const activityTypeMap = {
  0: "In Vehicle",
  1: "Biking",
  2: "On Foot",
  3: "Still",
  4: "Unknown",
  7: "Walking",
  8: "Running",
  9: "Aerobics",
  10: "Badminton",
  11: "Baseball",
  12: "Basketball",
  13: "Biathlon",
  14: "Handbiking",
  15: "Mountain Biking",
  16: "Road Biking",
  17: "Spinning",
  18: "Stationary Biking",
  19: "Utility Biking",
  20: "Boxing",
  21: "Calisthenics",
  22: "Circuit Training",
  23: "Cricket",
  24: "Dancing",
  25: "Elliptical",
  26: "Fencing",
  27: "Football (American)",
  28: "Football (Australian)",
  29: "Football (Soccer)",
  30: "Frisbee",
  31: "Gardening",
  32: "Golf",
  33: "Gymnastics",
  34: "Handball",
  35: "HIIT",
  36: "Hiking",
  37: "Hockey",
  38: "Horseback Riding",
  39: "Housework",
  40: "Jumping Rope",
  41: "Kayaking",
  42: "Kettlebell Training",
  43: "Kickboxing",
  44: "Kitesurfing",
  45: "Martial Arts",
  46: "Meditation",
  47: "Mixed Martial Arts",
  48: "P90X Exercises",
  49: "Paragliding",
  50: "Pilates",
  51: "Polo",
  52: "Racquetball",
  53: "Rock Climbing",
  54: "Rowing",
  55: "Rowing Machine",
  56: "Rugby",
  57: "Jogging",
  58: "Sailing",
  59: "Scuba Diving",
  60: "Skateboarding",
  61: "Skating",
  62: "Cross Skating",
  63: "Inline Skating",
  64: "Skiing",
  65: "Backcountry Skiing",
  66: "Cross-Country Skiing",
  67: "Downhill Skiing",
  68: "Kite Skiing",
  69: "Roller Skiing",
  70: "Sledding",
  71: "Snowboarding",
  72: "Snowmobile",
  73: "Snowshoeing",
  74: "Squash",
  75: "Stair Climbing",
  76: "Stair-Climbing Machine",
  77: "Stand-Up Paddleboarding",
  78: "Strength Training",
  79: "Surfing",
  80: "Swimming",
  81: "Swimming (Open Water)",
  82: "Swimming (Pool)",
  83: "Table Tennis",
  84: "Team Sports",
  85: "Tennis",
  86: "Treadmill",
  87: "Volleyball",
  88: "Volleyball (Beach)",
  89: "Volleyball (Indoor)",
  90: "Wakeboarding",
  91: "Walking (Fitness)",
  92: "Nording Walking",
  93: "Walking (Treadmill)",
  94: "Water Polo",
  95: "Weightlifting",
  96: "Wheelchair",
  97: "Windsurfing",
  98: "Yoga",
  99: "Zumba",
  100: "Diving",
  101: "Ergometer",
  102: "Ice Skating",
  103: "Indoor Skating",
  104: "Curling",
  105: "Other"
};